name: jupiter
favicon: null
layout_spectrum: 0.7276752642355859
typography_spectrum: 0.897061258321628
title: 'Jupiter Jones |'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9927620785310864
  lightness: 0.5667044185101986
  saturation: 0.8050102358683944
  rhythmicContrast: 0.44897294510155916
purpose: []
